baseurl = "//darioseyb.com/" # 

title = "Pretty Pixels"
copyright = "&copy; 2018 Dario Seyb"
languageCode = "en-us"
theme = "hugo-academic"

# Enable comments by entering your Disqus shortname
disqusShortname = "das-prettypixels"

# Enable analytics by entering your Google Analytics tracking ID
googleAnalytics = "UA-36574384-2"

[params]
  name = "Dario Seyb"
  role = "PhD Student"
  description = "Making Pretty Pictures with Math"
  organization = "Dartmouth College"
  avatar = "profile.png"
  email = "Dario.R.Seyb.GR@dartmouth.edu"
  address = "Hanover, NH, US."
  phone = "+491601634577"
  image = "projects/zaphod.png"
  twitterHandle = "@daseyb"

  # Date format (refer to Go's date format: http://flippinggodateformat.com )
  #   Examples: "Mon, Jan 2, 2006" or "2006-01-02"
  date_format = "Mon, Jan 2, 2006"

  # Enable global LaTeX math rendering? If false, you can enable it locally on a per page basis.
  math = true

  # Enable native social sharing buttons?
  sharing = true

  # Link custom CSS and JS assets (relative to /static/css and /static/js respectively)
  custom_css = []
  custom_js  = []

  # Biography section.
  # Section will only be displayed if `content/home/about.md` exists.
  [params.about]
    interests = ["Computer Graphics", "Game Development", "Realtime Rendering"]
    str_interests = "Interests"
    str_education = "Education"
 
    [[params.about.education]]
      course = "PhD in Computer Science"
      institution = "Dartmouth College"
      year = "2018 - present"

    [[params.about.education]]
      course = "BSc in Computer Science"
      institution = "RWTH Aachen University"
      year = "2014 - 2018"
      thesis = "A Multi-layered Approach to Embedded Mesh Deformation"

    [[params.about.education]]
      course = "Abitur"
      institution = "Leibniz Oberschule"
      year = 2013
      thesis = "Realtime Simulation of Rigidbodies in Two Dimensional Space"

  # Projects section.
  # Section will only be displayed if there are projects in `content/project/`.
  [params.projects]
    count = 5
    title = "Selected Projects"
    subtitle = ""
    str_all = "View All"

  # Selected Publications section.
  # Section will only be displayed if there are publications with `selected = true` in their `+++` preamble.
  [params.publications_selected]
    detailed_list = true
    title = "Selected Publications"
    subtitle = ""

  # Publications section.
  # Section will only be displayed if there are publications in `content/publication/`.
  [params.publications]
    count = 10
    detailed_list = false
    title = "Recent Publications"
    subtitle = ""
    str_all = "More Publications"

  # Posts section.
  # Section will only be displayed if there are posts in `content/post/`.
  [params.posts]
    count = 3
    title = "Recent Posts"
    subtitle = ""
    str_all = "View All"
    str_read_more = "Read more"

  # Gallery section.
  # Section will only be displayed if there are posts in `content/gallery/`.
  [params.gallery]
    count = 6
    title = "Gallery"
    subtitle = ""
    str_all = "View All"

  # Contact section.
  [params.contact]
    enable = false
    title = "Contact"
    subtitle = ""
    autolink = true  # Automatically link email and phone?

  # Social/Academic Networking
  #
  # Icon pack "fa" includes the following social network icons:
  #   twitter, weibo, linkedin, github, facebook, pinterest, google-plus, youtube, instagram, soundcloud
  #   For email icon, use "fa" icon pack, "envelope" icon, and "mailto:your@email.com" as the link.
  #   Full list: https://fortawesome.github.io/Font-Awesome/icons/
  #
  # Icon pack "ai" includes the following academic network icons:
  #   google-scholar, arxiv, orcid, researchgate, mendeley
  #   Full list: https://jpswalsh.github.io/academicons/

  [[params.social]]
    icon = "envelope"
    icon_pack = "fa"
    link = "mailto:Dario.R.Seyb.GR@dartmouth.edu"

  [[params.social]]
    icon = "twitter"
    icon_pack = "fa"
    link = "//twitter.com/daseyb"
  
  [[params.social]]
    icon = "github"
    icon_pack = "fa"
    link = "//github.com/daseyb"

  [[params.social]]
    icon = "linkedin"
    icon_pack = "fa"
    link = "//de.linkedin.com/in/darioseyb"

# Navigation Links
#   The weight parameter defines the order that the links will appear in.

[[menu.main]]
  name = "Home"
  url = "#top"
  weight = 1

[[menu.main]]
  name = "Gallery"
  url = "#gallery"
  weight = 2

[[menu.main]]
  name = "Posts"
  url = "#posts"
  weight = 3

[[menu.main]]
  name = "Projects"
  url = "#projects"
  weight = 4





